/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualkeybord;

import java.awt.AWTException;
import java.awt.event.KeyEvent;
import java.awt.Robot;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Keyboard extends javax.swing.JFrame {

    /**
     * Creates new form keyboard
     */
    public Keyboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQ = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnW = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnCedilha = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnUm = new javax.swing.JButton();
        btnDois = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnQuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnSete = new javax.swing.JButton();
        btnOito = new javax.swing.JButton();
        btnNove = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnSpace = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btnVirgula = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnInterrogacao = new javax.swing.JButton();
        btnShift = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        paragramaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        btnQ.setBackground(new java.awt.Color(255, 255, 255));
        btnQ.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnQ.setText("Q");
        btnQ.setBorderPainted(false);
        btnQ.setName("A"); // NOI18N
        btnQ.setOpaque(false);
        btnQ.setPreferredSize(new java.awt.Dimension(60, 50));
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        btnW.setBackground(new java.awt.Color(255, 255, 255));
        btnW.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnW.setText("W");
        btnW.setName("A"); // NOI18N
        btnW.setPreferredSize(new java.awt.Dimension(60, 50));
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });

        btnE.setBackground(new java.awt.Color(255, 255, 255));
        btnE.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnE.setText("E");
        btnE.setName("A"); // NOI18N
        btnE.setPreferredSize(new java.awt.Dimension(60, 50));
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnR.setBackground(new java.awt.Color(255, 255, 255));
        btnR.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnR.setText("R");
        btnR.setName("A"); // NOI18N
        btnR.setPreferredSize(new java.awt.Dimension(60, 50));
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        btnY.setBackground(new java.awt.Color(255, 255, 255));
        btnY.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnY.setText("Y");
        btnY.setName("A"); // NOI18N
        btnY.setPreferredSize(new java.awt.Dimension(60, 50));
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });

        btnT.setBackground(new java.awt.Color(255, 255, 255));
        btnT.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnT.setText("T");
        btnT.setName("A"); // NOI18N
        btnT.setPreferredSize(new java.awt.Dimension(60, 50));
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        btnU.setBackground(new java.awt.Color(255, 255, 255));
        btnU.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnU.setText("U");
        btnU.setName("A"); // NOI18N
        btnU.setPreferredSize(new java.awt.Dimension(60, 50));
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        btnI.setBackground(new java.awt.Color(255, 255, 255));
        btnI.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnI.setText("I");
        btnI.setName("A"); // NOI18N
        btnI.setPreferredSize(new java.awt.Dimension(60, 50));
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });

        btnO.setBackground(new java.awt.Color(255, 255, 255));
        btnO.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnO.setText("O");
        btnO.setName("A"); // NOI18N
        btnO.setPreferredSize(new java.awt.Dimension(60, 50));
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });

        btnP.setBackground(new java.awt.Color(255, 255, 255));
        btnP.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnP.setText("P");
        btnP.setName("A"); // NOI18N
        btnP.setPreferredSize(new java.awt.Dimension(60, 50));
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnG.setBackground(new java.awt.Color(255, 255, 255));
        btnG.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnG.setText("G");
        btnG.setName("A"); // NOI18N
        btnG.setPreferredSize(new java.awt.Dimension(60, 50));
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnJ.setBackground(new java.awt.Color(255, 255, 255));
        btnJ.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnJ.setText("J");
        btnJ.setName("A"); // NOI18N
        btnJ.setPreferredSize(new java.awt.Dimension(60, 50));
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });

        btnK.setBackground(new java.awt.Color(255, 255, 255));
        btnK.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnK.setText("K");
        btnK.setName("A"); // NOI18N
        btnK.setPreferredSize(new java.awt.Dimension(60, 50));
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });

        btnL.setBackground(new java.awt.Color(255, 255, 255));
        btnL.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnL.setText("L");
        btnL.setName("A"); // NOI18N
        btnL.setPreferredSize(new java.awt.Dimension(60, 50));
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        btnCedilha.setBackground(new java.awt.Color(255, 255, 255));
        btnCedilha.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCedilha.setText("Ç");
        btnCedilha.setName("A"); // NOI18N
        btnCedilha.setPreferredSize(new java.awt.Dimension(60, 50));
        btnCedilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCedilhaActionPerformed(evt);
            }
        });

        btnA.setBackground(new java.awt.Color(255, 255, 255));
        btnA.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnA.setText("A");
        btnA.setName("A"); // NOI18N
        btnA.setPreferredSize(new java.awt.Dimension(60, 50));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnS.setBackground(new java.awt.Color(255, 255, 255));
        btnS.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnS.setText("S");
        btnS.setName("A"); // NOI18N
        btnS.setPreferredSize(new java.awt.Dimension(60, 50));
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        btnD.setBackground(new java.awt.Color(255, 255, 255));
        btnD.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnD.setText("D");
        btnD.setName("A"); // NOI18N
        btnD.setPreferredSize(new java.awt.Dimension(60, 50));
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnF.setBackground(new java.awt.Color(255, 255, 255));
        btnF.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnF.setText("F");
        btnF.setName("A"); // NOI18N
        btnF.setPreferredSize(new java.awt.Dimension(60, 50));
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        btnH.setBackground(new java.awt.Color(255, 255, 255));
        btnH.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnH.setText("H");
        btnH.setName("A"); // NOI18N
        btnH.setPreferredSize(new java.awt.Dimension(60, 50));
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });

        btnX.setBackground(new java.awt.Color(255, 255, 255));
        btnX.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnX.setText("X");
        btnX.setName("A"); // NOI18N
        btnX.setPreferredSize(new java.awt.Dimension(60, 50));
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(255, 255, 255));
        btnC.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnC.setText("C");
        btnC.setName("A"); // NOI18N
        btnC.setPreferredSize(new java.awt.Dimension(60, 50));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnV.setBackground(new java.awt.Color(255, 255, 255));
        btnV.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnV.setText("V");
        btnV.setName("A"); // NOI18N
        btnV.setPreferredSize(new java.awt.Dimension(60, 50));
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });

        btnN.setBackground(new java.awt.Color(255, 255, 255));
        btnN.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnN.setText("N");
        btnN.setName("A"); // NOI18N
        btnN.setPreferredSize(new java.awt.Dimension(60, 50));
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        btnB.setBackground(new java.awt.Color(255, 255, 255));
        btnB.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnB.setText("B");
        btnB.setName("A"); // NOI18N
        btnB.setPreferredSize(new java.awt.Dimension(60, 50));
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        btnM.setBackground(new java.awt.Color(255, 255, 255));
        btnM.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnM.setText("M");
        btnM.setName("A"); // NOI18N
        btnM.setPreferredSize(new java.awt.Dimension(60, 50));
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnZ.setBackground(new java.awt.Color(255, 255, 255));
        btnZ.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnZ.setText("Z");
        btnZ.setName("A"); // NOI18N
        btnZ.setPreferredSize(new java.awt.Dimension(60, 50));
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });

        btnUm.setBackground(new java.awt.Color(255, 255, 255));
        btnUm.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnUm.setText("<html> &nbsp ! <br> 1 </html>");
        btnUm.setBorderPainted(false);
        btnUm.setName("A"); // NOI18N
        btnUm.setOpaque(false);
        btnUm.setPreferredSize(new java.awt.Dimension(60, 50));
        btnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmActionPerformed(evt);
            }
        });

        btnDois.setBackground(new java.awt.Color(255, 255, 255));
        btnDois.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDois.setText("<html> &nbsp @ <br> 2 </html>");
        btnDois.setName("A"); // NOI18N
        btnDois.setPreferredSize(new java.awt.Dimension(60, 50));
        btnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoisActionPerformed(evt);
            }
        });

        btnTres.setBackground(new java.awt.Color(255, 255, 255));
        btnTres.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTres.setText("<html> &nbsp #<br> 3 </html>");
        btnTres.setName("A"); // NOI18N
        btnTres.setPreferredSize(new java.awt.Dimension(60, 50));
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnQuatro.setBackground(new java.awt.Color(255, 255, 255));
        btnQuatro.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnQuatro.setText("<html> &nbsp $ <br> 4 </html>");
        btnQuatro.setName("A"); // NOI18N
        btnQuatro.setPreferredSize(new java.awt.Dimension(60, 50));
        btnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuatroActionPerformed(evt);
            }
        });

        btnCinco.setBackground(new java.awt.Color(255, 255, 255));
        btnCinco.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCinco.setText("<html> &nbsp % <br> 5 </html>");
        btnCinco.setName("A"); // NOI18N
        btnCinco.setPreferredSize(new java.awt.Dimension(60, 50));
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnSeis.setBackground(new java.awt.Color(255, 255, 255));
        btnSeis.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSeis.setText("<html> &nbsp ¨ <br> 6 </html>");
        btnSeis.setName("A"); // NOI18N
        btnSeis.setPreferredSize(new java.awt.Dimension(60, 50));
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnSete.setBackground(new java.awt.Color(255, 255, 255));
        btnSete.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSete.setText("<html> &nbsp & <br> 7 </html>");
        btnSete.setName("A"); // NOI18N
        btnSete.setPreferredSize(new java.awt.Dimension(60, 50));
        btnSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeteActionPerformed(evt);
            }
        });

        btnOito.setBackground(new java.awt.Color(255, 255, 255));
        btnOito.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnOito.setText("<html> &nbsp * <br> 8 </html>");
        btnOito.setName("A"); // NOI18N
        btnOito.setPreferredSize(new java.awt.Dimension(60, 50));
        btnOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOitoActionPerformed(evt);
            }
        });

        btnNove.setBackground(new java.awt.Color(255, 255, 255));
        btnNove.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnNove.setText("<html> &nbsp ( <br> 9 </html>");
        btnNove.setName("A"); // NOI18N
        btnNove.setPreferredSize(new java.awt.Dimension(60, 50));
        btnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoveActionPerformed(evt);
            }
        });

        btnZero.setBackground(new java.awt.Color(255, 255, 255));
        btnZero.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnZero.setText("<html> &nbsp ) <br> 0 </html>");
        btnZero.setName("A"); // NOI18N
        btnZero.setPreferredSize(new java.awt.Dimension(60, 50));
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnSpace.setBackground(new java.awt.Color(255, 255, 255));
        btnSpace.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        btnEnter.setBackground(new java.awt.Color(255, 255, 255));
        btnEnter.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEnter.setText("Enter");
        btnEnter.setName("A"); // NOI18N
        btnEnter.setPreferredSize(new java.awt.Dimension(50, 40));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnVirgula.setBackground(new java.awt.Color(255, 255, 255));
        btnVirgula.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnVirgula.setText(",");
        btnVirgula.setName("A"); // NOI18N
        btnVirgula.setPreferredSize(new java.awt.Dimension(60, 50));
        btnVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVirgulaActionPerformed(evt);
            }
        });

        btnPonto.setBackground(new java.awt.Color(255, 255, 255));
        btnPonto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnPonto.setText(".");
        btnPonto.setName("A"); // NOI18N
        btnPonto.setPreferredSize(new java.awt.Dimension(60, 50));
        btnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontoActionPerformed(evt);
            }
        });

        btnInterrogacao.setBackground(new java.awt.Color(255, 255, 255));
        btnInterrogacao.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnInterrogacao.setText("?");
        btnInterrogacao.setName("A"); // NOI18N
        btnInterrogacao.setPreferredSize(new java.awt.Dimension(60, 50));
        btnInterrogacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterrogacaoActionPerformed(evt);
            }
        });

        btnShift.setBackground(new java.awt.Color(255, 255, 255));
        btnShift.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnShift.setText("Shift");
        btnShift.setName("A"); // NOI18N
        btnShift.setPreferredSize(new java.awt.Dimension(50, 40));
        btnShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShiftActionPerformed(evt);
            }
        });

        btnBackspace.setBackground(new java.awt.Color(255, 255, 255));
        btnBackspace.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnBackspace.setText("backspace");
        btnBackspace.setName("A"); // NOI18N
        btnBackspace.setPreferredSize(new java.awt.Dimension(50, 40));
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        paragramaLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        paragramaLabel.setText("Digite Enter para começar.  =D");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnInterrogacao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnShift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(99, 99, 99)
                                                    .addComponent(btnSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnCedilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnSete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(paragramaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paragramaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCedilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInterrogacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int i=0;
    int nivelMaximo = 5;
    int nivel=1;
    boolean flag = false;
    
    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed

    }//GEN-LAST:event_btnQActionPerformed
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        pangrama pangrama = new pangrama();
        if(nivel > nivelMaximo){
            nivel = 1;
        }
        
        pangrama.setNivel(nivel);
        
        paragramaLabel.setText(pangrama.pangrams_nivel());
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void brilhaTeclado(int evt, int red_back, int green_back, int blue_back, int red_Font, int green_Font, int blue_Font){
        switch(evt){
            case KeyEvent.VK_Q:
                btnQ.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnQ.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_W:
                btnW.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnW.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_E:
                btnE.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnE.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_R:
                btnR.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnR.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_T:
                btnT.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnT.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_Y:
                btnY.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnY.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_U:
                btnU.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnU.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_I:
                btnI.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnI.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_O:
                btnO.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnO.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_P:
                btnP.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnP.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_A:
                btnA.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnA.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_S:
                btnS.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnS.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_D:
                btnD.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnD.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_F:
                btnF.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnF.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_G:
                btnG.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnG.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_H:
                btnH.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnH.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_J:
                btnJ.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnJ.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_K:
                btnK.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnK.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_L:
                btnL.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnL.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_Z:
                btnZ.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnZ.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_X:
                btnX.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnX.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_C:
                btnC.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnC.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_V:
                btnV.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnV.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_B:
                btnB.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnB.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_N:
                btnN.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnN.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_M:
                btnM.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnM.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_SPACE:
                btnSpace.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnSpace.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_SHIFT:
                btnShift.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnShift.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_ENTER:
                btnEnter.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnEnter.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_BACK_SPACE:
                btnBackspace.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnBackspace.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_COMMA:
                btnVirgula.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnVirgula.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_PERIOD:
                btnPonto.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnPonto.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_UNDEFINED:
                btnCedilha.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnCedilha.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_1:
                btnUm.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnUm.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_2:
                btnDois.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnDois.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_3:
                btnTres.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnTres.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_4:
                btnQuatro.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnQuatro.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_5:
                btnCinco.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnCinco.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_6:
                btnSeis.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnSeis.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_7:
                btnSete.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnSete.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_8:
                btnOito.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnOito.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_9:
                btnNove.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnNove.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
            case KeyEvent.VK_0:
                btnZero.setBackground(new java.awt.Color(red_back,green_back,blue_back));
                btnZero.setForeground(new java.awt.Color(red_Font,green_Font,blue_Font));
                break;
        }
        
    }
    
    private void textoDigitadoCerto() throws AWTException{
        char[] pangrama = paragramaLabel.getText().toCharArray();
        int tamanho = pangrama.length;
        char[] usuario = jTextField1.getText().toCharArray();
        if(i<=tamanho){
            if(usuario[i] == pangrama[i]){
                System.out.print(i);
                System.out.print(usuario[i]);
                i ++;
                jTextField1.setBackground(new java.awt.Color(240,240,240));
                if(i == tamanho){
                    nivel ++;
                    i = 0;
                    Robot robot = new Robot();
                    robot.keyPress(10);
                    robot.keyRelease(10);
                }
            }else{
                jTextField1.setBackground(new java.awt.Color(255,102,102));
            }
        }
    }
    
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        this.brilhaTeclado(evt.getKeyCode(), 255, 25, 32, 240, 240, 240); 
        if(evt.getKeyCode() != KeyEvent.VK_ENTER){
            try {
                this.textoDigitadoCerto();
            } catch (AWTException ex) {
                Logger.getLogger(Keyboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed
    
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        this.brilhaTeclado(evt.getKeyCode(), 240, 240, 240, 0, 0, 0);
        if(evt.getKeyCode() != KeyEvent.VK_ENTER){
            try {
                this.textoDigitadoCerto();
            } catch (AWTException ex) {
                Logger.getLogger(Keyboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLActionPerformed

    private void btnCedilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCedilhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCedilhaActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZActionPerformed

    private void btnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUmActionPerformed

    private void btnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoisActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeteActionPerformed

    private void btnOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOitoActionPerformed

    private void btnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoveActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVirgulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVirgulaActionPerformed

    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPontoActionPerformed

    private void btnInterrogacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterrogacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInterrogacaoActionPerformed

    private void btnShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShiftActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackspaceActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>      
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Keyboard().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCedilha;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDois;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnInterrogacao;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnNove;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnOito;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnQuatro;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSete;
    private javax.swing.JButton btnShift;
    private javax.swing.JButton btnSpace;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnUm;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnVirgula;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JButton btnZero;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel paragramaLabel;
    // End of variables declaration//GEN-END:variables

}
